# all builds should be covered 
[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[unstable]
# use rusts' premade memory fns over libc ones
build-std-features = ["compiler-builtins-mem"]
# recompile the core and compilier bulitin libraries
build-std = ["core", "compiler_builtins"]

[build]
# set the default build target
target = "x86_64-buildData.json"